### ISSUE TITLE
tapping on invisible parts of outlined shapes produces notifications

### ISSUE THREAD

**Issue by CSchank** [MacCASOutreach/graphicsvg#27]
Outlined shapes produce messages when users interact with supposedly invisible / non-existent parts of the shapes -- this reflects an overall problem in how filling / outlining works -- shapes that are `outlined` are actually filled with no opacity in SVG. We should avoid placing `fill` and `fill-opacity` attributes altogether on shapes which are just outlined.

**Comment by GordonBGood** [comment]
I just checked this, and without `fill` or `fillOpacity` attributes it just defaults to opaque black which is still clickable.  With only the `fillOpacity` it is transparent, but it is also still clickable...

I can't come up with a way of simply and automatically doing what is desired - making opaque areas including masked areas of Shape's not respond to notifications.  The only way I can get working is to simulate just an outline using lines and/or curves, which gives the desired behavior but isn't simple to create automatically, especially for circles or ovals...

**Comment by GordonBGood** [comment]
Yes, leave it open in case someone knows something that can help about SVG, but I'm afraid that even if they do, it will mean doing changes to the SVG library which could take some time.  As well, we've boiled down the SVG features used to a small set that seem to work consistently across browsers; I'm worried that if we do anything esoteric that may work with some browsers may not in others (something like "clippath").

As to "time it would take to develop and test", not so long - I could probably do a PR in less than a week.  It helps that even a `wedge` is approximated with a polygon so an outline is just a matter of converting the list of points forming the different polygons to lists of polyline points.  The only curved shapes are circles, ovals, and rounded rectangles, and ovals can be thought of as just circles that are "squeezed" along one axis and rounded rectangles take the four quarters of a circle in the corners with some special processing for when the radius is bigger than half the minimum of the width and height.

As to performance, in these cases we'd be eliminating the actual drawing of the filled shapes so there would actually be a win when we are replacing them with just lines; in the curves case, the Bezier curves calculations are no doubt done by a highly optimized library in the browser and we only need about 16 points to do a reasonable approximation of a circle so it likely isn't much of a factor and likely would take no more time than the highly optimized library filling circles, ovals, and rounded rectangles.

As to complexity, it will add a little in the processing (`createSVG`) of the "Inked" shapes, but I think it can be minimized and localized to only there.

Adding to InteractiveTest to test each of the stencils singly and in groups as to notification response isn't so hard.

If you'd like me to go ahead with a PR, just say the word...

**Comment by GordonBGood** [comment]
After more investigations, the secret is very simple:  one needs to set the `fill` Attribute on the body to "none" and then its as if the area isn't there...

It still needs a little logic on when to apply this, but it turns out to be very easy.  Give me a day for testing and I'll submit a further PR.

**Comment by CSchank** [comment]
Great! I figured there must be a way, seemed like a pretty big oversight if not. Thank you!

**Comment by GordonBGood** [comment]
I've almost competed testing and will post the PR in a few hours.

It works for all stencils except for `Text`, which apparently has a transparent invisible background area which is revealed through the interior of text when `fill = "none"` but also surrounds the text area to a set distance; this attached transparent background is a part of the `Text` and blocks all notifications to any other object which is revealed beneath it.

All information on the Internet seems to indicate that this text background is not controllable by any known `Attribute` as to make it fill to "none" and, if true, there seems to be nothing that can be done about the `Text` stencil.

Following all the other tests that show that all other stencils are "click-through", I have added a final InteractiveTest which fails showing that `Text` is not "click-through" in case someone discovers a way to work around this.

**Comment by CSchank** [comment]
Great, thank you. The text isn't a big deal. Usually, we have the opposite problem with text: it's too hard to tap! So we can keep an eye out and maybe leave an issue open for someone who knows something. Any solution might not be, as you mentioned, very accepted across platforms. I'll approve the PR tomorrow morning then maybe we can push the non-commutative linear algebra update soon. Thanks again for all of your hard and meticulous work (on testing, etc too!)

**Comment by CSchank** [comment]
Fixed in f1df9dc48325ce00b5eff7f0bd739cc19d9ac1ff and then further in 58ae0caa4ac3c373720fcb78414330108d2c2233 and eb5a9b84a9d4cba58ef6a621c0db592ee2f38a4b
