### ISSUE TITLE
Exposing Types in GraphicSVG.Secret Module in v8.0.0

### ISSUE THREAD

**Issue by ccamel** [MacCASOutreach/graphicsvg#43]
For my project [ccamel/playground-elm](https://github.com/ccamel/playground-elm), I'm using version `7.2.0` of [MacCASOutreach/graphicsvg](https://github.com/MacCASOutreach) - amazing library btw.

Upon upgrading to version `8.0.0` and reviewing the changes made, I noticed that several key types of `GraphicSVG` module have been shifted into their own module, `GraphicSVG.Secret`. While some of these types are aliased and publicly exposed, such as `Stencil` or `Shape`, others like `Color` or `LineType` are no longer available, types that I use in my code.

Of course, I can revise my code to eliminate the need for these types, enabling me to switch to the latest version. I completely understand the reasons behind these changes, however, I'm curious about the rationale for making these specific types private.

Thanks! :pray:

**Comment by CSchank** [comment]
Hi @ccamel, thanks for reaching out. We sort of arbitrarily chose these ones to expose, knowing that our codebases use them the most, but we're sorry it messed up your codebase. I think there's no reason for us not to expose those. I'll do that shortly. I'm getting a weird error with Elm when it comes to trying to run `elm diff` to deploy a new version of the package. For now, I recommend just sitting tight on 7.2.0. We didn't really update anything else in the 8.0.0 release, other than moving the types around so we can use the constructors for more advanced projects and shape analytics, etc.

**Comment by CSchank** [comment]
Hi @ccamel, I have published 8.1.0, this should address your issue! Let me know if you need any more help, or if it doesn't work!! All the best.

**Comment by ccamel** [comment]
@CSchank Excellent, it worked flawlessly! Thank you.

**Comment by CSchank** [comment]
Great, you're welcome! Enjoy :)
